# Generated by Django 5.0.7 on 2024-07-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d9', models.CharField(default='0', max_length=255)),
                ('usdt', models.CharField(default='0', max_length=255)),
            ],
        ),
    ]
