# Generated by Django 5.0.7 on 2024-07-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0002_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyreserves',
            name='d9_to_usdt',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='currencyreserves',
            name='usdt_to_d9',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='currencyreserves',
            name='d9',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='currencyreserves',
            name='usdt',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
