# Generated by Django 5.0.7 on 2024-07-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccumulativeRewardPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totals', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totals', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TotalVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totals', models.CharField(max_length=255)),
            ],
        ),
    ]
