# Generated by Django 5.0.7 on 2024-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USDTBalance',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('balance_usdt', models.CharField(blank=True, default='0', max_length=255, null=True)),
            ],
        ),
    ]
