# Generated by Django 5.0.7 on 2024-07-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account_name', models.CharField(blank=True, default='default', max_length=255, null=True)),
                ('balance_d9', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('balance_usdt', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('node_name', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('node_reward', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('d9_equal_usdt', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('usdt_equal_usdt', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('total_value', models.CharField(blank=True, default='0', max_length=255, null=True)),
            ],
        ),
    ]
