# Generated by Django 5.0.7 on 2024-07-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('node_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=255)),
                ('sharing_percent', models.CharField(max_length=255)),
                ('accumulative_votes', models.CharField(max_length=255)),
            ],
        ),
    ]
