# Generated by Django 5.0.7 on 2024-07-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranks',
            name='accumulative_votes',
            field=models.IntegerField(),
        ),
    ]
