# Generated by Django 5.0.7 on 2024-07-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantExpiry',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
