# Generated by Django 5.0.7 on 2024-07-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantexpiry',
            name='expiry_date',
            field=models.CharField(default='1567958400', max_length=255),
        ),
    ]
